version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: AWSSDK.DynamoDBv2
    versions:
    - 3.7.0.16
    - 3.7.0.2
  - dependency-name: AWSSDK.SimpleEmail
    versions:
    - 3.7.0.1
